# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: saasen
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OGMzZmYwZWY4MmYwMWMzMmRjZjZkNDBhMDQ2MDUxODY2OGI5YzJjZDE4ODkxZmU0ZmFhMzRjY2MyYjlmNmM5YmQyZjBjNzc3NjY2MmZiMTE5NmU2OGMwMzVmZThmNGQzM2FmMWFmYThlMDZmMDU2YWZlZDI4YzdjMmE5ODAxMmU=
