package com.saasen.nl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssignedResourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssignedResourceAllPropertiesEquals(AssignedResource expected, AssignedResource actual) {
        assertAssignedResourceAutoGeneratedPropertiesEquals(expected, actual);
        assertAssignedResourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssignedResourceAllUpdatablePropertiesEquals(AssignedResource expected, AssignedResource actual) {
        assertAssignedResourceUpdatableFieldsEquals(expected, actual);
        assertAssignedResourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssignedResourceAutoGeneratedPropertiesEquals(AssignedResource expected, AssignedResource actual) {
        assertThat(actual)
            .as("Verify AssignedResource auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssignedResourceUpdatableFieldsEquals(AssignedResource expected, AssignedResource actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssignedResourceUpdatableRelationshipsEquals(AssignedResource expected, AssignedResource actual) {
        assertThat(actual)
            .as("Verify AssignedResource relationships")
            .satisfies(a ->
                assertThat(a.getResourceAvailability()).as("check resourceAvailability").isEqualTo(expected.getResourceAvailability())
            )
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
