package com.saasen.nl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FreelancerAssignmentRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerAssignmentRequestAllPropertiesEquals(
        FreelancerAssignmentRequest expected,
        FreelancerAssignmentRequest actual
    ) {
        assertFreelancerAssignmentRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertFreelancerAssignmentRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerAssignmentRequestAllUpdatablePropertiesEquals(
        FreelancerAssignmentRequest expected,
        FreelancerAssignmentRequest actual
    ) {
        assertFreelancerAssignmentRequestUpdatableFieldsEquals(expected, actual);
        assertFreelancerAssignmentRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerAssignmentRequestAutoGeneratedPropertiesEquals(
        FreelancerAssignmentRequest expected,
        FreelancerAssignmentRequest actual
    ) {
        assertThat(actual)
            .as("Verify FreelancerAssignmentRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerAssignmentRequestUpdatableFieldsEquals(
        FreelancerAssignmentRequest expected,
        FreelancerAssignmentRequest actual
    ) {
        assertThat(actual)
            .as("Verify FreelancerAssignmentRequest relevant properties")
            .satisfies(a -> assertThat(a.getRequestedAt()).as("check requestedAt").isEqualTo(expected.getRequestedAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerAssignmentRequestUpdatableRelationshipsEquals(
        FreelancerAssignmentRequest expected,
        FreelancerAssignmentRequest actual
    ) {
        assertThat(actual)
            .as("Verify FreelancerAssignmentRequest relationships")
            .satisfies(a -> assertThat(a.getFreelancer()).as("check freelancer").isEqualTo(expected.getFreelancer()))
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
