package com.saasen.nl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FreelancerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerAllPropertiesEquals(Freelancer expected, Freelancer actual) {
        assertFreelancerAutoGeneratedPropertiesEquals(expected, actual);
        assertFreelancerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerAllUpdatablePropertiesEquals(Freelancer expected, Freelancer actual) {
        assertFreelancerUpdatableFieldsEquals(expected, actual);
        assertFreelancerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerAutoGeneratedPropertiesEquals(Freelancer expected, Freelancer actual) {
        assertThat(actual)
            .as("Verify Freelancer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerUpdatableFieldsEquals(Freelancer expected, Freelancer actual) {
        assertThat(actual)
            .as("Verify Freelancer relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getContact()).as("check contact").isEqualTo(expected.getContact()))
            .satisfies(a -> assertThat(a.getQualification()).as("check qualification").isEqualTo(expected.getQualification()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFreelancerUpdatableRelationshipsEquals(Freelancer expected, Freelancer actual) {
        // empty method
    }
}
