package com.saasen.nl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InstructorAvailabilityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorAvailabilityAllPropertiesEquals(InstructorAvailability expected, InstructorAvailability actual) {
        assertInstructorAvailabilityAutoGeneratedPropertiesEquals(expected, actual);
        assertInstructorAvailabilityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorAvailabilityAllUpdatablePropertiesEquals(
        InstructorAvailability expected,
        InstructorAvailability actual
    ) {
        assertInstructorAvailabilityUpdatableFieldsEquals(expected, actual);
        assertInstructorAvailabilityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorAvailabilityAutoGeneratedPropertiesEquals(
        InstructorAvailability expected,
        InstructorAvailability actual
    ) {
        assertThat(actual)
            .as("Verify InstructorAvailability auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorAvailabilityUpdatableFieldsEquals(InstructorAvailability expected, InstructorAvailability actual) {
        assertThat(actual)
            .as("Verify InstructorAvailability relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getAvailableFrom()).as("check availableFrom").isEqualTo(expected.getAvailableFrom()))
            .satisfies(a -> assertThat(a.getAvailableTo()).as("check availableTo").isEqualTo(expected.getAvailableTo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstructorAvailabilityUpdatableRelationshipsEquals(
        InstructorAvailability expected,
        InstructorAvailability actual
    ) {
        assertThat(actual)
            .as("Verify InstructorAvailability relationships")
            .satisfies(a -> assertThat(a.getInstructor()).as("check instructor").isEqualTo(expected.getInstructor()));
    }
}
