package com.saasen.nl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LocationAvailabilityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationAvailabilityAllPropertiesEquals(LocationAvailability expected, LocationAvailability actual) {
        assertLocationAvailabilityAutoGeneratedPropertiesEquals(expected, actual);
        assertLocationAvailabilityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationAvailabilityAllUpdatablePropertiesEquals(LocationAvailability expected, LocationAvailability actual) {
        assertLocationAvailabilityUpdatableFieldsEquals(expected, actual);
        assertLocationAvailabilityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationAvailabilityAutoGeneratedPropertiesEquals(LocationAvailability expected, LocationAvailability actual) {
        assertThat(actual)
            .as("Verify LocationAvailability auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationAvailabilityUpdatableFieldsEquals(LocationAvailability expected, LocationAvailability actual) {
        assertThat(actual)
            .as("Verify LocationAvailability relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getAvailableFrom()).as("check availableFrom").isEqualTo(expected.getAvailableFrom()))
            .satisfies(a -> assertThat(a.getAvailableTo()).as("check availableTo").isEqualTo(expected.getAvailableTo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationAvailabilityUpdatableRelationshipsEquals(LocationAvailability expected, LocationAvailability actual) {
        assertThat(actual)
            .as("Verify LocationAvailability relationships")
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()));
    }
}
