package com.saasen.nl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequestedCourseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedCourseAllPropertiesEquals(RequestedCourse expected, RequestedCourse actual) {
        assertRequestedCourseAutoGeneratedPropertiesEquals(expected, actual);
        assertRequestedCourseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedCourseAllUpdatablePropertiesEquals(RequestedCourse expected, RequestedCourse actual) {
        assertRequestedCourseUpdatableFieldsEquals(expected, actual);
        assertRequestedCourseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedCourseAutoGeneratedPropertiesEquals(RequestedCourse expected, RequestedCourse actual) {
        assertThat(actual)
            .as("Verify RequestedCourse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedCourseUpdatableFieldsEquals(RequestedCourse expected, RequestedCourse actual) {
        assertThat(actual)
            .as("Verify RequestedCourse relevant properties")
            .satisfies(a ->
                assertThat(a.getNumberOfParticipants()).as("check numberOfParticipants").isEqualTo(expected.getNumberOfParticipants())
            )
            .satisfies(a ->
                assertThat(a.getPreferredStartDate()).as("check preferredStartDate").isEqualTo(expected.getPreferredStartDate())
            )
            .satisfies(a -> assertThat(a.getPreferredLocation()).as("check preferredLocation").isEqualTo(expected.getPreferredLocation()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getActualStartDate()).as("check actualStartDate").isEqualTo(expected.getActualStartDate()))
            .satisfies(a -> assertThat(a.getActualEndDate()).as("check actualEndDate").isEqualTo(expected.getActualEndDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestedCourseUpdatableRelationshipsEquals(RequestedCourse expected, RequestedCourse actual) {
        assertThat(actual)
            .as("Verify RequestedCourse relationships")
            .satisfies(a -> assertThat(a.getTrainingRequest()).as("check trainingRequest").isEqualTo(expected.getTrainingRequest()))
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()));
    }
}
