package com.saasen.nl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResourceAvailabilityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAvailabilityAllPropertiesEquals(ResourceAvailability expected, ResourceAvailability actual) {
        assertResourceAvailabilityAutoGeneratedPropertiesEquals(expected, actual);
        assertResourceAvailabilityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAvailabilityAllUpdatablePropertiesEquals(ResourceAvailability expected, ResourceAvailability actual) {
        assertResourceAvailabilityUpdatableFieldsEquals(expected, actual);
        assertResourceAvailabilityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAvailabilityAutoGeneratedPropertiesEquals(ResourceAvailability expected, ResourceAvailability actual) {
        assertThat(actual)
            .as("Verify ResourceAvailability auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAvailabilityUpdatableFieldsEquals(ResourceAvailability expected, ResourceAvailability actual) {
        assertThat(actual)
            .as("Verify ResourceAvailability relevant properties")
            .satisfies(a -> assertThat(a.getAvailableFrom()).as("check availableFrom").isEqualTo(expected.getAvailableFrom()))
            .satisfies(a -> assertThat(a.getAvailableTo()).as("check availableTo").isEqualTo(expected.getAvailableTo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAvailabilityUpdatableRelationshipsEquals(ResourceAvailability expected, ResourceAvailability actual) {
        assertThat(actual)
            .as("Verify ResourceAvailability relationships")
            .satisfies(a -> assertThat(a.getResource()).as("check resource").isEqualTo(expected.getResource()));
    }
}
