package com.saasen.nl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionAllPropertiesEquals(Session expected, Session actual) {
        assertSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionAllUpdatablePropertiesEquals(Session expected, Session actual) {
        assertSessionUpdatableFieldsEquals(expected, actual);
        assertSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionAutoGeneratedPropertiesEquals(Session expected, Session actual) {
        assertThat(actual)
            .as("Verify Session auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionUpdatableFieldsEquals(Session expected, Session actual) {
        assertThat(actual)
            .as("Verify Session relevant properties")
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionUpdatableRelationshipsEquals(Session expected, Session actual) {
        assertThat(actual)
            .as("Verify Session relationships")
            .satisfies(a ->
                assertThat(a.getInstructorAvailability()).as("check instructorAvailability").isEqualTo(expected.getInstructorAvailability())
            )
            .satisfies(a ->
                assertThat(a.getLocationAvailability()).as("check locationAvailability").isEqualTo(expected.getLocationAvailability())
            )
            .satisfies(a -> assertThat(a.getRequestedCourse()).as("check requestedCourse").isEqualTo(expected.getRequestedCourse()))
            .satisfies(a -> assertThat(a.getFreelancer()).as("check freelancer").isEqualTo(expected.getFreelancer()));
    }
}
