package com.saasen.nl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrainingRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRequestAllPropertiesEquals(TrainingRequest expected, TrainingRequest actual) {
        assertTrainingRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertTrainingRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRequestAllUpdatablePropertiesEquals(TrainingRequest expected, TrainingRequest actual) {
        assertTrainingRequestUpdatableFieldsEquals(expected, actual);
        assertTrainingRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRequestAutoGeneratedPropertiesEquals(TrainingRequest expected, TrainingRequest actual) {
        assertThat(actual)
            .as("Verify TrainingRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRequestUpdatableFieldsEquals(TrainingRequest expected, TrainingRequest actual) {
        assertThat(actual)
            .as("Verify TrainingRequest relevant properties")
            .satisfies(a -> assertThat(a.getRequestDate()).as("check requestDate").isEqualTo(expected.getRequestDate()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingRequestUpdatableRelationshipsEquals(TrainingRequest expected, TrainingRequest actual) {
        assertThat(actual)
            .as("Verify TrainingRequest relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
